### PR TITLE
Optimisation of Speed

### PR DESCRIPTION
**Pull request by fgrunewald**
Small optimisation for building large polymers and placing solvents.

### CODE REVIEW

**Comment by ricalessandri** [comment]
@fgrunewald shall I do a small benchmark with the main branch and this branch? I could test a polymer melt and a single-chain simulation, tomorrow.

**Comment by fgrunewald** [comment]
@ricalessandri that would be fantastic; I briefly checked on Mac and should be fine. When you go for the melt you need to provide a bending option via the build file. I recommend trying a long chain perhaps 1500 residues. That is what one part of the speed-opt addresses. For PS you could use:

```
[ bending ]
PS PS PS 3
```

Using this bending setup we actually can generate a correct number of entanglements. I've done some benchmarking on the melt structures in the past week. Overall, I'm surprised how good they are if you provide a bending constant. Hopefully, I manage to share the details in Denver. 

The other part addresses polymer solutions. If you build a box of just water or polymer solvent mixture it should be significantly faster now and more linear in scaling.

**Comment by ricalessandri** [comment]
@fgrunewald I've tested the melt, making a fresh install just in case:
```
conda create -n polyply-speedopt python=3
conda activate polyply-speedopt
conda install -c conda numpy
conda install -c conda scipy
conda install -c conda numba
git clone git@github.com:marrink-lab/polyply_1.0.git polyply_1.0-speedopt
cd polyply_1.0-speedopt
pip install -e .
```
Then:
```
dens="1400"

cd polyply_1.0-speedopt
git checkout speedopt
echo "Polyply version: $(python -c "import polyply; print(polyply.__version__)")"   >  ../test_log_${dens}.txt
echo "Current Git commit: $(git rev-parse HEAD)"                                    >> ../test_log_${dens}.txt
echo "Current Git branch: $(git rev-parse --abbrev-ref HEAD)"                       >> ../test_log_${dens}.txt
cd ..

# PS
{ time polyply gen_coords -p system_melt.top -o test_melt.gro -name test_melt -dens ${dens} -b build_file.bld; } 2>> test_log_${dens}.txt

cd polyply_1.0-speedopt
git checkout master
echo "Polyply version: $(python -c "import polyply; print(polyply.__version__)")"   >> ../test_log_${dens}.txt
echo "Current Git commit: $(git rev-parse HEAD)"                                    >> ../test_log_${dens}.txt
echo "Current Git branch: $(git rev-parse --abbrev-ref HEAD)"                       >> ../test_log_${dens}.txt
cd ..

# PS
{ time polyply gen_coords -p system_melt.top -o test_melt.gro -name test_melt -dens ${dens} -b build_file.bld; } 2>> test_log_${dens}.txt
```

Which gives:
```
Polyply version: 1.7.1.dev47
Current Git commit: 6f168af11457ee68978110fad99b835661e6fc36
Current Git branch: speedopt
INFO - step - reading topology
INFO - step - processing topology
INFO - step - reading build options
INFO - step - generating templates
100%|██████████| 1000/1000 [00:02<00:00, 403.64it/s]
INFO - step - annotating ligands
INFO - step - generating system coordinates
100%|██████████| 1000/1000 [01:06<00:00, 14.98it/s]
INFO - step - backmapping to target resolution
100%|██████████| 1000/1000 [00:38<00:00, 26.02it/s]
INFO - step - writing output

real	2m5.287s
user	2m1.618s
sys	0m3.044s
Polyply version: 1.7.1.dev47
Current Git commit: c820aaa5e6da7bd8340b360a2a4453fca4d52138
Current Git branch: master
INFO - step - reading topology
INFO - step - processing topology
INFO - step - reading build options
INFO - step - generating templates
100%|██████████| 1000/1000 [00:02<00:00, 400.26it/s]
INFO - step - annotating ligands
INFO - step - generating system coordinates
100%|██████████| 1000/1000 [01:07<00:00, 14.91it/s]
INFO - step - backmapping to target resolution
100%|██████████| 1000/1000 [00:39<00:00, 25.13it/s]
INFO - step - writing output

real	2m6.855s
user	2m3.037s
sys	0m2.980s
```

I don't see much of a speed-up, but maybe the system needs to be even larger?
This is the system (gives a ~25^3 nm^3):
```
; Martini 3 particle definitions and interaction matrix
#include "/Users/alessandri/ric.alessandri_v2/Repos/Martini/itps/martini_v300/martini_v3.0.0.itp"
; Topologies of molecules in the system
#include "PS_n1500.itp"
[ system ]
PS melt
[ molecules ]
PS      1000
```

**Comment by fgrunewald** [comment]
@ricalessandri are you sure your polymer is 1500 units? 25^3nm^3 seems very small for that many residues?

**Comment by ricalessandri** [comment]
@fgrunewald good catch, I had indeed a typo in my itp generation script. I've repeated the test with an actual M3 PS with 1500 residues. For a system with 1000x 1500-mers (the box is ~63^3 nm^3), **I do find a speed-up of ~30%** (!), see below:
```
Polyply version: 1.7.1.dev47
Current Git commit: 6f168af11457ee68978110fad99b835661e6fc36
Current Git branch: speedopt
INFO - step - reading topology
INFO - step - processing topology
INFO - step - reading build options
INFO - step - generating templates
100%|██████████| 1000/1000 [00:35<00:00, 28.08it/s]
INFO - step - annotating ligands
INFO - step - generating system coordinates
100%|██████████| 1000/1000 [18:29<00:00,  1.11s/it]
INFO - step - backmapping to target resolution
100%|██████████| 1000/1000 [09:24<00:00,  1.77it/s]
INFO - step - writing output

real	33m36.302s
user	32m5.119s
sys	0m57.532s
Polyply version: 1.7.1.dev47
Current Git commit: c820aaa5e6da7bd8340b360a2a4453fca4d52138
Current Git branch: master
INFO - step - reading topology
INFO - step - processing topology
INFO - step - reading build options
INFO - step - generating templates
100%|██████████| 1000/1000 [00:35<00:00, 27.97it/s]
INFO - step - annotating ligands
INFO - step - generating system coordinates
100%|██████████| 1000/1000 [18:07<00:00,  1.09s/it]
INFO - step - backmapping to target resolution
100%|██████████| 1000/1000 [09:47<00:00,  1.70it/s]
INFO - step - writing output

real	48m31.518s
user	32m14.350s
sys	0m43.759s
```

**Review by pckroon — APPROVED** [review]
Do you get different results now that small molecules are not part of the nonbond_matrix?

**Comment by fgrunewald** [comment]
@pckroon they are still part of the nonbond_matrix; just the partitioning of the trees is differently

**Comment by pckroon** [comment]
I thought so, but better to be sure ;)

**Pull request merged**
