### PR TITLE
Convert P3HT.martini3.itp to P3HT.martini3.ff

### PR DESCRIPTION
**Pull request by ricalessandri**
I am encountering some issue when doing this conversion, namely:

1. **"i-j-k" bonded terms**, i.e., bonded terms spanning across 3 repeat units: connections between monomer N and N-1 won't get printed after the last N-2--N-1--N connection gets printed; don't know if I'm doing something wrong here.?
   The line responsible is commented out:
```
;  V4  +V4 ++V4    1       158      180  {"comment": "i-j-k"}
```

2. **[ exclusions ]** are not handheld by the .ff format --> https://github.com/marrink-lab/polyply_1.0/issues/134; 
   Lines are commented out:
```
;[ exclusions ]
;; between nearest-neighbor thiophenes 
;   S1  +S1  +C2  +C3                    {"comment": "connection"} 
;   C2  +S1  +C2  +C3                    {"comment": "connection"}
;   C3  +S1  +C2  +C3                    {"comment": "connection"}
```

3. **[ virtual_sitesn ]**: in the [ virtual_sitesn ] section, also the function type is shifted by N_monomer_atoms.
    I'm gonna comment about it in this issue: https://github.com/marrink-lab/polyply_1.0/issues/120

This is the correct output for an hexamer: https://github.com/marrink-lab/polyply_1.0/blob/master/polyply/tests/test_data/library_tests/martini3/P3HT/polyply/P3HT.itp

### CODE REVIEW

**Comment by fgrunewald** [comment]
@ricalessandri exclusions and VS I answered about in the relevant issues. I also put the tag FAQ. I think those will be very valuable to add to the FAQ section. 

Regarding the N and N+2 links. Basically that is what I outlined when you were asking about why I split angles, dihedrals and bonds into separate link for gromos. In order for a link to apply the entire fragment has to be present. That means when you have an angle that spans three residues the entire link will only apply when all three residues are present. That means towards the end of your polymer you will not have any links because when there are only two residues left. As a rule of thumb each interaction in the same link should span the same residues

**Comment by ricalessandri** [comment]
Great, now I understood the need for re-defining the link - that's pretty OK.

I also updated the reference itp for the tests (and now all the checks pass - I guess that was the reason the checks were breaking).

**Comment by fgrunewald** [comment]
@ricalessandri looks good to me. There is just one thing I don't understand. How is the reference file you have now different from the one that is generated by P3HT.martini3.itp? Shouldn't they be the same?

**Comment by ricalessandri** [comment]
Well, you can see the differences:
https://github.com/marrink-lab/polyply_1.0/pull/135/files#diff-f6f68e6a69bc3649043d658f6c7e005e562187bf8d522c2e547d4906836cd8ec
namely:
- now the command is printed on the first line (`; /Users/riccardo/miniconda3/envs/polyply/bin/polyply gen_itp -lib martini3 -name P3HT -seq P3HT:6 -o P3HT_n6_M3.itp`) and there's the `; Please cite the following papers:` bit
- I added a comment to the i-j-k connection (`; connection i-j-k`)
- changed the function type of the VS from 2 (-> COM) to 1 (->COG) (but it doesn't really matter)
- the lines in the `[exclusions]` are printed in a different order

**Comment by ricalessandri** [comment]
Ready to go - unless you want to include via this PR also the versions with
different side chain lengths and the "reversed" monomer which is needed to
create regiorandom P3HT (which btw "solves" issue
https://github.com/marrink-lab/polyply_1.0/issues/91). If not, please merge
this PR and I will open a dedicated PR for those.

**Comment by fgrunewald** [comment]
@ricalessandri let's merge this first. We add the other topologies when the test-case is done. Perhaps we'll have to adjust those anyways to improve the test case. No harm in having more than 1 PR.

**Pull request merged**
