### PR TITLE
Add input files for Martini2 ssDNA [2]

### PR DESCRIPTION
**Pull request by fgrunewald**
Adds the library files for Martini2 ssDNA.

### CODE REVIEW

**Comment by fgrunewald** [comment]
@BartBruininks could you provide me with a sample sequence and itp file for the M2 DNA?

**Comment by fgrunewald** [comment]
@jan-stevens can you generate a Martini2 ssDNA strand of some sequence like this one https://www.genomatix.de/online_help/help/sequence_formats.html and add it to the library tests of this branch. I'd like to merge it ideally this week before the BPS conference.

**Comment by jan-stevens** [comment]
I added the library test for M2 ssDNA, it however fails. It seems that there is a difference between how the `martinize-dna.py` and `gen_params` construct the ssDNA, could it be that they use a different martini2 dna version?

**Comment by fgrunewald** [comment]
This is a strange one again. On two local machines the test works only on the CI it seems to miss some of the angles???

**Review by jan-stevens — APPROVED** [review]
Looks good to me!

**Pull request merged**
