### PR TITLE
Add OPLS-AA LigParGen PEO to the library

### PR DESCRIPTION
**Pull request by ricalessandri**
Here's PEO with OPLS-AA using parameters obtained from the [LigParGen server](http://zarbi.chem.yale.edu/ligpargen/). Works good. Can generated a OH terminated PEO like this:

```
polyply gen_itp -lib oplsaa_LigParGen_polymers -name PEO -seq OHter:1 PEO:50 OHter:1 -o PEO_n50_opls.itp
```

To run, you need the following in the `top`:
```
; Include forcefield parameters
#include "/usr/local/gromacs-XXXX/share/gromacs/top/oplsaa.ff/forcefield.itp"
#include "atom_types_LigParGen.itp"
...
etc.
```

where `atom_types_LigParGen.itp` looks like this:
```
; GENERATED BY LigParGen Server
; Jorgensen Lab @ Yale University
;
[ atomtypes ]
  opls_800  C800   12.0110     0.000    A    3.50000E-01   2.76144E-01 ; C
  opls_801  O801   15.9990     0.000    A    2.90000E-01   5.85760E-01 ; O
  opls_802  H802    1.0080     0.000    A    2.50000E-01   1.25520E-01 ; H
  opls_803  O803   15.9990     0.000    A    3.12000E-01   7.11280E-01 ; O (ALCOHOL, TERMINI)
```

I left the atom type definitions as a comment on the header of `PEO.oplsaa.LigParGen.ff` - probably not the best idea on the long run... 

Man, we really should figure out how to automagically take an itp generated from servers such as [LigParGen server](http://zarbi.chem.yale.edu/ligpargen/) and by entering which atoms belong to the block and which belong to a termini, generate automatically all the necessary blocks and links.! I would be up for taking on such a task at some point but I'd need some guidance from you code masters on how to do this in the smartest way possible :)

### CODE REVIEW

**Review by fgrunewald — CHANGES_REQUESTED** [review]
Looks good to me, except for the fact that the atomtypes are missing a column. At least to be consistent with the opls def in the gromacs repository the atomnumber should be added. Otherwise we get a parsing error. It remains a miracle to me as to how gromacs knows which fields can be omitted. I'll need to do a big dive to see what happens. 

I also already produced some morphologies. That seems to work fine. @ricalessandri  can you also try one two systems with the new defaults? The mdps I took from Caleman and I was doing the energy minimization with flexible bonds.

**Comment by fgrunewald** [comment]
@ricalessandri did you try building a system? If yes then we can merge this or not?

**Comment by ricalessandri** [comment]
I did not to build a PEO OPLS melt but I'm trying a PS OPLS melt and having some difficulties. But it's my first AA melts so.. they are more delicate. I'll try more tomorrow.

**Comment by fgrunewald** [comment]
@ricalessandri I tried building this PEO OPLS system and it seems fine to me. I could energy minimize and run a Berendsen at 1fs for some nano seconds.

**Comment by ricalessandri** [comment]
Yes, OPLS PEO looks good. I run the melt for a while. It needs flexible bonds for the energy minimization and some 10s of ns of equilibration but we knew that's needed for AA systems.

I added the test following the instructions at https://github.com/marrink-lab/polyply_1.0/pull/112#issuecomment-826108758. So I'd say this PR is good to go.

**Review by fgrunewald — APPROVED** [review]

**Pull request merged**
