### PR TITLE
add all tutorial files

### PR DESCRIPTION
**Pull request by fgrunewald**
These are the tutorial files corresponding to the Tutorials on the wiki and also the example test-cases of the battery and LLPS from the paper.

### CODE REVIEW

**Review by pckroon — COMMENTED** [review]
If you want me to review this, please separate the code/scripts from the data into different commits. Is there any reason why the random comb is in the tutorial files rather than the library?
Should the tutorial folder be excluded from the deployment? There should be an option in pbr somewhere.

**Comment by fgrunewald** [comment]
@pckroon you don't need to review the content. Just small feedback on if we want to include it like this. The random-lin-comb is not general and very single purpose only for that example. I don't intend to make it part of gen_seq for now.

**Comment by pckroon** [comment]
There's quite a bit of lint in the random comb code, but looks ok otherwise. 
As for whether we want to include it this way, I think we discussed that before: You kind of want to separate the martini3 parameters into their own repo, and the same goes for the binary.

**Comment by fgrunewald** [comment]
@pckroon I've made a central repository for the M3 parameters and deleted unnecessary files. As each martini parameter file is already ~16MB, these changes reduce the size by half. Now it is only 34MB. I also did some (light) linting on random-comb. The binary I'd like to keep with the example test case as the intention is not to redistribute it but to enable reviewers or other people to run the code on Linux without the need of installing an additional program. Later we can perhaps integrate it into polyply to deal with solvation.

**Pull request merged**
