### PR TITLE
More link definitions for building block copolymers

### PR DESCRIPTION
**Pull request by ricalessandri**
For now, I just added one more link to allow building of PEO-PE block copolymers, which seems to be necessary as explained in https://github.com/marrink-lab/polyply_1.0/issues/91.  More links, if needed, could be added as part of this pull request.

### CODE REVIEW

**Review by fgrunewald — APPROVED** [review]
Looks good to me from an M2 point of view.

**Review by fgrunewald — CHANGES_REQUESTED** [review]
Actually can you implement a test for this? You need to add one more section in here: https://github.com/marrink-lab/polyply_1.0/blob/master/polyply/tests/test_itp_gen.py.
After line 65 add a ',' then add inbetween 65 and 66

```
  (["-lib", "martini2_polymers",
         "-seqf", TEST_DATA + "/gen_itp/input/PEO_PE.json",
         "-name", "PEO_PE",
         "-o", TEST_DATA + "/gen_itp/output/PEO_b_PE_out.itp"]
```
Then you need to put a reference itp file in the folder tests/test_data/gen_itp/ref and add the sequence file into input located one folder above. Note that the molecule name needs to be PEO_PEOref in the reference file. 

Once you have done that go to the directory polyply/tests/ and run pytest test_itp_gen.py. It might be that you have to run an `pip install --upgrade -r requirements-tests.txt` from the top level directory first. If all goes well the output should be all green and you then just commit the change and push it to this branch. Otherwise do it as well and also mention the error. 

Adding tests is important to keep the libraries sane.

**Comment by ricalessandri** [comment]
Done. You forgot one line on that block but I figured it - have a look at the latest commit. All test passed. 

```
==================================================== test session starts ====================================================
platform darwin -- Python 3.8.5, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/riccardo/polyply_1.0
plugins: cov-2.11.1
collected 8 items                                                                                                           

test_itp_gen.py ........                                                                                              [100%]

===================================================== 8 passed in 1.58s =====================================================
```

**Review by fgrunewald — APPROVED** [review]
@ricalessandri thanks for fixing this! Parameters look good to me. I'll merge it as soon as our CI workflow works again. Apparently we are out of CPU hours with Travis, so we are looking into switching the platform.

**Comment by fgrunewald** [comment]
@ricalessandri Can you merge master into this repository? The automatic workflow should be triggered by that.

**Comment by ricalessandri** [comment]
> @ricalessandri Can you merge master into this repository? The automatic workflow should be triggered by that.

@fgrunewald I think I just did what you asked for, have a look. It took me a little to figure it out. I think mostly because I shouldn't have implemented things on my master branch but instead should have created a dedicated branch for this..

**Comment by fgrunewald** [comment]
@ricalessandri whatever you did in the end, this looks good.

**Pull request merged**
