### PR TITLE
add function to generate complementary DNA strand for dsDNA

### PR DESCRIPTION
**Pull request by fgrunewald**
The changes in this branch allow for a sequence representing a single strand of DNA to be complemented by the corresponding base-pairs to form the dsDNA strand.

### CODE REVIEW

**Review by jan-stevens — APPROVED** [review]
The implementation looks good to me!

**Comment by fgrunewald** [comment]
@jan-stevens is it a problem if both strands in the metamolecule run 5' -> 3' in terms of their node indices?

**Comment by jan-stevens** [comment]
@fgrunewald  That should not be a problem, since the annotator picks one strand as reference and then checks all other strands and reversed strands for the best complementary match.

**Review by jbarnoud — APPROVED** [review]

**Comment by fgrunewald** [comment]
This has turned into quite a mess of different branches somehow evolving together. I'm gonna retire it and make a new clean PR.

**Pull request closed without merging**
