### PR TITLE
add PC lipids for pegylation

### PR DESCRIPTION
**Pull request by fgrunewald**
Implementation of PEGylation for M2 and M3 lipids following the crude scheme of Lee and the M2 PEG paper by myself. 

@ricalessandri  can you have a brief look if anything is missing?

### CODE REVIEW

**Comment by ricalessandri** [comment]
The bonded connections look good to me. A couple of questions I have (the first due to my limited peg-lipid knowledge): 
- so you keep the negative charge of bead number 2 of the lipid and remove only the charge on the first lipid bead?
-  there's a small inconsistency: the links in the `martini2` folder are in the links.ff and in the martini3 folder in the `PEL_link.ff`. Of course, this doesn't affect polyply's behavior but it might be confusing for the (semi-)expert user.

**Review by ricalessandri — APPROVED** [review]
See my previous (non-mandatory) comment

**Comment by fgrunewald** [comment]
@ricalessandri thanks for the comments. Regarding the first the choice is still based on the old Lee convention from 2013/2011. Basically you attach the PEG via the choline/amine headgroup of the PC, PE lipid and thus it becomes charge neutral. We probably should be looking at remapping those but it's actually not so trivial to find a working atomistic FF. I think the Charmm GUI had a recent paper.

**Comment by fgrunewald** [comment]
in fact PC lipids cannot be PEGylated. The Martini2 implementation is the same as a PEGylated PE lipid. So I'd rather not implement the wrong name.

**Pull request closed without merging**
