### PR TITLE
Add PTMA CG M3 model to polyply library [arXiv:2209.02072]

### PR DESCRIPTION
**Pull request by ricalessandri**
Contributing the Martini 3 CG model developed for PTMA in https://arxiv.org/abs/2209.02072.

Test to follow.

### CODE REVIEW

**Review by fgrunewald — COMMENTED** [review]
Looks good. Should we add a test to the library tests for this one?

**Comment by ricalessandri** [comment]
If you don't do this ([5b4d858](https://github.com/marrink-lab/polyply_1.0/pull/277/commits/5b4d85888e579e63666cfcc6ae4ab5e215b0b132)), the citations reader breaks, btw.

**Comment by ricalessandri** [comment]
Test added - I think that's it (if the test goes well).

**Review by fgrunewald — APPROVED** [review]
Looks good!

**Comment by fgrunewald** [comment]
> If you don't do this ([5b4d858](https://github.com/marrink-lab/polyply_1.0/pull/277/commits/5b4d85888e579e63666cfcc6ae4ab5e215b0b132)), the citations reader breaks, btw.

Yeah the bib text parser is not ideal but the bib text format is also a really and format, because there are multiple standards. If we could find someone to take care of this would be great.

**Pull request merged**
